const mongoose = require("mongoose");
const Listing = require("./models/Listing");

mongoose.connect("mongodb+srv://landsureUser:Amoghy%4023@cluster0.fkot8rm.mongodb.net/LandSureProject?retryWrites=true&w=majority&appName=Cluster0")
    .then(() => console.log("MongoDB connected"))
    .catch(err => console.log(err));

const listings = [
    {
        title: "Mulshi, Pune",
        location: "Mulshi",
        price: 1050000,
        area: "32 acres",
        type: "Agricultural land",
        direction: "North",
        soil: "Clay",
        water: "Well access",
        legal: "Clear title",
        ownerName: "Kapoor Group",
        ownerContact: "+91-9876543210",
        ownerEmail: "kapoor@example.com",
        ownerAddress: "Mulshi, Pune",
        ownerNotes: "Contact only via email",
        landmarks: "Near Mulshi Lake",
        roadDistance: "500m from main road",
        envNotes: "Fertile soil, moderate slope",
        devPotential: "Good for farm projects",
        description: "Fertile agricultural land with easy water access.",
        imageUrl: "https://i.pinimg.com/1200x/68/f5/84/68f584ea98cf3a09c2287721bcc02dac.jpg",
        isFeatured: true,
        featuredPaidAmount: 10000,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    
    {
        title: "PR, Punawale",
        location: "Punawale",
        price: 4000000,
        area: "1 acre",
        type: "Agricultural land",
        direction: "East",
        soil: "Sandy loam",
        water: "Borewell access",
        legal: "Registered",
        ownerName: "Punawale Estates",
        ownerContact: "+91-9123456780",
        ownerEmail: "contact@punawale.com",
        ownerAddress: "Punawale, Pune",
        ownerNotes: "Available for inspection on weekends",
        landmarks: "Next to IT Park",
        roadDistance: "200m from main road",
        envNotes: "Good sunlight exposure",
        devPotential: "High for residential development",
        description: "Prime agricultural plot near main road.",
        imageUrl: "https://99realty.in/wp-content/uploads/2023/08/Residential-Land.jpg",
        isFeatured: true,
        featuredPaidAmount: 5000,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Presedential Park, Kanhe",
        location: "Talegaon",
        price: 5400000,
        area: "30,000 sq. ft.",
        type: "Residential land",
        direction: "South",
        soil: "Loamy",
        water: "Municipal supply",
        legal: "Clear title",
        ownerName: "Amogh Yadav",
        ownerContact: "+91-9988776655",
        ownerEmail: "amogh@example.com",
        ownerAddress: "Talegaon, Pune",
        ownerNotes: "Prefers direct call",
        landmarks: "Near Talegaon Station",
        roadDistance: "1km from main road",
        envNotes: "Peaceful neighborhood",
        devPotential: "Ideal for villa construction",
        description: "Residential plot in gated community with amenities.",
        imageUrl: "https://www.presidentialpark.in/assets/imgs/about%20us%201929x18421.webp",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Patil lands",
        location: "Bendewadi",
        price: 20000000,
        area: "5 acres",
        type: "Agricultural land",
        direction: "West",
        soil: "Clay",
        water: "Canal access",
        legal: "Under process",
        ownerName: "Amogh Yadav",
        ownerContact: "+91-9988776656",
        ownerEmail: "amogh2@example.com",
        ownerAddress: "Bendewadi, Pune",
        ownerNotes: "Visit by appointment only",
        landmarks: "Near Bendewadi Hills",
        roadDistance: "300m from main road",
        envNotes: "Fertile, needs minor leveling",
        devPotential: "High for organic farming",
        description: "Spacious agricultural land suitable for farming.",
        imageUrl: "https://www.hdwallpapers.in/download/beautiful_view_of_farm_land_hd_nature-1920x1080.jpg",
        isFeatured: true,
        featuredPaidAmount: 7000,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Godrej Estates",
        location: "Hinjewadi",
        price: 25000000,
        area: "2, 3, 4 BHK",
        type: "Residential land",
        direction: "North-East",
        soil: "Sandy loam",
        water: "Municipal water",
        legal: "Registered",
        ownerName: "Godrej Pvt. Ltd.",
        ownerContact: "+91-9123456789",
        ownerEmail: "godrej@example.com",
        ownerAddress: "Hinjewadi, Pune",
        ownerNotes: "Preferred buyers only",
        landmarks: "Near IT Park",
        roadDistance: "50m from main road",
        envNotes: "Well-developed neighborhood",
        devPotential: "High for residential towers",
        description: "Premium residential land in Hinjewadi IT hub.",
        imageUrl: "https://is1-2.housingcdn.com/4f2250e8/25e7ba3e398822879381d4fd11969a96/v0/fs/godrej_river_greens-manjari_khurd_1-pune-godrej_properties_ltd.jpg",
        isFeatured: true,
        featuredPaidAmount: 10000,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Dream lands",
        location: "Talegaon",
        price: 2000000,
        area: "1 acre",
        type: "Agricultural land",
        direction: "South-East",
        soil: "Loamy",
        water: "Borewell",
        legal: "Clear",
        ownerName: "Dream11",
        ownerContact: "+91-9876543211",
        ownerEmail: "dream11@example.com",
        ownerAddress: "Talegaon, Pune",
        ownerNotes: "Quick sale",
        landmarks: "Near Talegaon Market",
        roadDistance: "100m from main road",
        envNotes: "Good soil, sunny",
        devPotential: "Low, for personal farming",
        description: "Affordable agricultural land for small scale farming.",
        imageUrl: "https://cdn.wallpapersafari.com/63/86/XAtxeN.jpg",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Omkar Residency",
        location: "Ravet",
        price: 5250000,
        area: "3, 4 BHK",
        type: "Residential land",
        direction: "West",
        soil: "Clay Loam",
        water: "Municipal water",
        legal: "Registered",
        ownerName: "Omkar Group",
        ownerContact: "+91-9123456790",
        ownerEmail: "omkar@example.com",
        ownerAddress: "Ravet, Pune",
        ownerNotes: "Inspection after call",
        landmarks: "Near Ravet Bus Stand",
        roadDistance: "150m from main road",
        envNotes: "Peaceful environment",
        devPotential: "Good for villas",
        description: "Residential plots in developing area.",
        imageUrl: "https://apnacomplexdocs.s3-ap-southeast-1.amazonaws.com/user_content/communities_photo/profile_picture.jpg",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Green Acres, Hinjewadi",
        location: "Hinjewadi",
        price: 15000000,
        area: "4 acres",
        type: "Agricultural land",
        direction: "North-West",
        soil: "Loamy",
        water: "Borewell access",
        legal: "Clear",
        ownerName: "Ankit Vadnere",
        ownerContact: "+91-9876543222",
        ownerEmail: "ankit@example.com",
        ownerAddress: "Hinjewadi, Pune",
        ownerNotes: "Contact via WhatsApp",
        landmarks: "Near Hinjewadi IT Park",
        roadDistance: "300m from main road",
        envNotes: "Fertile soil",
        devPotential: "Good for organic farming",
        description: "Large agricultural land near IT hub.",
        imageUrl: "https://images.pexels.com/photos/1483880/pexels-photo-1483880.jpeg?cs=srgb&dl=pexels-tomfisk-1483880.jpg&fm=jpg",
        isFeatured: true,
        featuredPaidAmount: 5000,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Lavasa Hills",
        location: "Lavasa",
        price: 35000000,
        area: "1 acre",
        type: "Residential land",
        direction: "South-West",
        soil: "Clay Loam",
        water: "Municipal water",
        legal: "Registered",
        ownerName: "Abhiram Nair",
        ownerContact: "+91-9988776699",
        ownerEmail: "abhiram@example.com",
        ownerAddress: "Lavasa, Pune",
        ownerNotes: "Serious buyers only",
        landmarks: "Near Lake",
        roadDistance: "500m from main road",
        envNotes: "Hilly area, scenic",
        devPotential: "High for villas",
        description: "Luxury residential plot in Lavasa Hills.",
        imageUrl: "https://www.commercialproperty.review/wp-content/uploads/2020/08/ATS-Greens-Village-Aparments-Sector-93-Noida.jpg",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Raj Garden, Kharadi",
        location: "Kharadi",
        price: 12000000,
        area: "2 acres",
        type: "Agricultural land",
        direction: "East",
        soil: "Loamy",
        water: "Borewell",
        legal: "Clear",
        ownerName: "Aditya Group",
        ownerContact: "+91-9123456791",
        ownerEmail: "aditya@example.com",
        ownerAddress: "Kharadi, Pune",
        ownerNotes: "Available weekdays",
        landmarks: "Near Kharadi IT Park",
        roadDistance: "200m from main road",
        envNotes: "Fertile soil",
        devPotential: "Medium",
        description: "Agricultural land suitable for small scale farming.",
        imageUrl: "https://images.pexels.com/photos/3013440/pexels-photo-3013440.jpeg?cs=srgb&dl=pexels-rafa-de-21730-3013440.jpg&fm=jpg",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Skyline Residency, Balewadi",
        location: "Balewadi",
        price: 18000000,
        area: "3 acres",
        type: "Residential land",
        direction: "North",
        soil: "Clay",
        water: "Municipal water",
        legal: "Registered",
        ownerName: "Runwal group",
        ownerContact: "+91-9988776688",
        ownerEmail: "runwal@example.com",
        ownerAddress: "Balewadi, Pune",
        ownerNotes: "Inspection on appointment",
        landmarks: "Near Stadium",
        roadDistance: "100m from main road",
        envNotes: "Well-connected area",
        devPotential: "High for apartments",
        description: "Residential land in prime location.",
        imageUrl: "https://www.piramalaranya.com/wp-content/uploads/2024/01/Rising-Demand-of-Residential-Projects-In-Mulund.png",
        isFeatured: true,
        featuredPaidAmount: 7000,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Sunny Farms, Mulshi",
        location: "Mulshi",
        price: 8000000,
        area: "5 acres",
        type: "Agricultural land",
        direction: "West",
        soil: "Sandy",
        water: "Canal access",
        legal: "Clear title",
        ownerName: "Aastha Tiwari",
        ownerContact: "+91-9123456792",
        ownerEmail: "aastha@example.com",
        ownerAddress: "Mulshi, Pune",
        ownerNotes: "Contact for visit",
        landmarks: "Near Mulshi Dam",
        roadDistance: "400m from main road",
        envNotes: "Good soil, fertile",
        devPotential: "Good for farmhouses",
        description: "Large agricultural plot with water access.",
        imageUrl: "https://images.pexels.com/photos/46160/field-clouds-sky-earth-46160.jpeg",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Shanti Residency, Baner",
        location: "Baner",
        price: 22500000,
        area: "2 acres",
        type: "Residential land",
        direction: "North-East",
        soil: "Loamy",
        water: "Municipal supply",
        legal: "Registered",
        ownerName: "Deshpande",
        ownerContact: "+91-9876543233",
        ownerEmail: "deshpande@example.com",
        ownerAddress: "Baner, Pune",
        ownerNotes: "Prefers weekend visits",
        landmarks: "Near Baner Hills",
        roadDistance: "150m from main road",
        envNotes: "Scenic neighborhood",
        devPotential: "High for villas",
        description: "Residential plot with excellent location.",
        imageUrl: "https://carajput.com/blog/wp-content/uploads/2018/01/shutterstock_728111731-1.jpg",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Vastu Farms, Ravet",
        location: "Ravet",
        price: 9500000,
        area: "3 acres",
        type: "Agricultural land",
        direction: "South",
        soil: "Clay",
        water: "Borewell",
        legal: "Clear",
        ownerName: "Madhavi Yadav",
        ownerContact: "+91-9988776677",
        ownerEmail: "madhavi@example.com",
        ownerAddress: "Ravet, Pune",
        ownerNotes: "Call before visiting",
        landmarks: "Near Ravet Lake",
        roadDistance: "200m from main road",
        envNotes: "Good soil, sunny",
        devPotential: "Medium",
        description: "Fertile agricultural land with good location.",
        imageUrl: "https://w0.peakpx.com/wallpaper/284/594/HD-wallpaper-field-in-the-heart-land-yield-crop-clouds-farm-season-heartland-land-rows-harvest-cloud-tractor-sky-skies-farmland-heart-nature-heart-land-crops-field.jpg",
        isFeatured: false,
        featuredPaidAmount: 0,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    },
    {
        title: "Orchid Residency, Hinjewadi",
        location: "Hinjewadi",
        price: 30000000,
        area: "1.5 acres",
        type: "Residential land",
        direction: "East",
        soil: "Loamy",
        water: "Municipal supply",
        legal: "Registered",
        ownerName: "Ram Kadu",
        ownerContact: "+91-9123456793",
        ownerEmail: "ram@example.com",
        ownerAddress: "Hinjewadi, Pune",
        ownerNotes: "Serious buyers only",
        landmarks: "Near Hinjewadi IT Park",
        roadDistance: "50m from main road",
        envNotes: "Well-developed area",
        devPotential: "High for villas",
        description: "Premium residential plot near IT hub.",
        imageUrl: "https://www.commercialproperty.review/wp-content/uploads/2020/10/Central-Park-Resorts-Apartments-Sector-48-Gurgaon-India-.jpeg",
        isFeatured: true,
        featuredPaidAmount: 10000,
        latitude: 18.501485159278683,
        longitude: 73.51351267839266
    }
];

async function seedDB() {
    try {
        await Listing.deleteMany({});
        await Listing.insertMany(listings);
        console.log("Listings inserted!");
        mongoose.connection.close();
    } catch (err) {
        console.log(err);
    }
}

seedDB();